components:
  schemas:
    Entry:
      properties:
        duration:
          example: '0:00:00.013737'
          type: string
        status:
          example: healthy
          type: string
        tags:
          items:
            example: db
            type: string
          type: array
      type: object
    EntryData:
      properties:
        name:
          $ref: '#/components/schemas/Entry'
      type: object
    HealthCheck:
      properties:
        entries:
          $ref: '#/components/schemas/EntryData'
        status:
          example: healthy
          type: string
        total_duration:
          example: '0:00:00.013737'
          type: string
      type: object
info:
  title: app
  version: 1.0.0
openapi: 3.0.2
paths:
  /alive:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
          description: Success response
      summary: Service Health Method
servers:
- description: null
  url: null
- description: 'Development server '
  url: http://localhost:5000
